# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Metropolis sampler using Rcpp
#' @name Metropolis_c
#' @description A Metropolis sampler using Rcpp.
#' @param N the number of samples
#' @param x0 initial value
#' @param sigma variance of samples
#' @return a random sample of size \code{N}
#' @importFrom Rcpp evalCpp
#' @examples
#' \dontrun{
#' N=1e3
#' sigma=2
#' x0=25
#' rw=Metropolis_c(N,x0,sigma)
#' }
#' @export
Metropolis_c <- function(N, x0, sigma) {
    .Call('_StatComp20080_Metropolis_c', PACKAGE = 'StatComp20080',N, x0, sigma)
}

